using Microsoft.Owin;
using Owin;

// Make sure you have installed Microsoft.Owin.Host.SystemWeb package in the project.
// This package is needed for startup detection in IIS hosted applications. 
// https://stackoverflow.com/a/20204884/1872200
[assembly: OwinStartup(typeof(Codesanook.Examples.AspNetMvc.Startup))]
namespace Codesanook.Examples.AspNetMvc
{
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            // Any connection or hub wire up and configuration should go here
            // This will create autogenerated SignalR hub script. ~/signalr/hubs-->
            app.MapSignalR();
        }
    }
}
